if(NOT DEFINED PHLOSION_ROOT)
    message(FATAL_ERROR "PHLOSION_ROOT is required")
endif()

set(GL_PATH "${PHLOSION_ROOT}/src/engine/render/opengl/OpenGLRenderBackendWorldPipeline.cpp")
set(D3D_PATH "${PHLOSION_ROOT}/src/engine/render/d3d12/D3D12RenderBackendWorldPipeline.cpp")
set(VK_MATERIAL_PATH "${PHLOSION_ROOT}/assets/shaders/vulkan/world_material.glsl")
set(VK_DIRECT_PATH "${PHLOSION_ROOT}/assets/shaders/vulkan/world.frag")
set(VK_INDIRECT_PATH "${PHLOSION_ROOT}/assets/shaders/vulkan/world_indirect.frag")

foreach(SOURCE_PATH IN ITEMS "${GL_PATH}" "${D3D_PATH}" "${VK_MATERIAL_PATH}")
    file(READ "${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "Exact SV SSS variation 56 samples diffuse irradiance")
        message(FATAL_ERROR "SV SSS source-role boundary is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "environmentDiffuse = sampleNeutralEnvironment")
        message(FATAL_ERROR "SV SSS diffuse-irradiance bridge is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "reflection = reflect" OR
       NOT SOURCE_TEXT MATCHES "-viewDirection")
        message(FATAL_ERROR "SV SSS reflection-vector bridge is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "environmentSpecular = sampleNeutralEnvironment")
        message(FATAL_ERROR "SV SSS roughness-filtered specular bridge is missing from ${SOURCE_PATH}")
    endif()
    if(SOURCE_TEXT MATCHES "0\\.34f? \\+ 0\\.78f? \\* wrappedNdotL")
        message(FATAL_ERROR "SV SSS regressed to the flat ambient approximation in ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "fibreSheen = fibreSurface" OR
       NOT SOURCE_TEXT MATCHES "qualityDetail \\* wrappedNdotL")
        message(FATAL_ERROR "The bounded Eevee fibre approximation changed in ${SOURCE_PATH}")
    endif()
endforeach()

foreach(SOURCE_PATH IN ITEMS "${VK_DIRECT_PATH}" "${VK_INDIRECT_PATH}")
    file(READ "${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "evaluateNativeSssSurface")
        message(FATAL_ERROR "Vulkan SSS call is missing from ${SOURCE_PATH}")
    endif()
    if(SOURCE_PATH STREQUAL VK_DIRECT_PATH)
        set(EXPECTED_ENVIRONMENT_ARGUMENT "                environmentTexture,")
    else()
        set(EXPECTED_ENVIRONMENT_ARGUMENT "                environmentTextures[nonuniformEXT(materialIndex)],")
    endif()
    string(FIND "${SOURCE_TEXT}" "${EXPECTED_ENVIRONMENT_ARGUMENT}" ENVIRONMENT_ARGUMENT_POSITION)
    if(ENVIRONMENT_ARGUMENT_POSITION EQUAL -1)
        message(FATAL_ERROR "Vulkan SSS call does not supply the shared environment in ${SOURCE_PATH}")
    endif()
endforeach()

message(STATUS "SV native SSS environment contract verified")
