if(NOT DEFINED PHLOSION_ROOT)
    message(FATAL_ERROR "PHLOSION_ROOT is required")
endif()

set(GL_PATH "${PHLOSION_ROOT}/src/engine/render/opengl/OpenGLRenderBackendWorldPipeline.cpp")
set(D3D_PATH "${PHLOSION_ROOT}/src/engine/render/d3d12/D3D12RenderBackendWorldPipeline.cpp")
set(VK_PATH "${PHLOSION_ROOT}/assets/shaders/vulkan/world_material.glsl")

foreach(SOURCE_PATH IN ITEMS "${GL_PATH}" "${D3D_PATH}" "${VK_PATH}")
    file(READ "${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "sampleZaLocalReflectionProbe")
        message(FATAL_ERROR "Z-A local-reflection sampler is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "faceSize \\* 4.*- 2")
        message(FATAL_ERROR "Z-A all-mip atlas qualification is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "mipStripY")
        message(FATAL_ERROR "Z-A authored mip-strip addressing is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "reflectionBlur \\+ max.*[Tt]extureDetailLodBias")
        message(FATAL_ERROR "Z-A ReflectionsBlur/quality LOD bridge is missing from ${SOURCE_PATH}")
    endif()
endforeach()

message(STATUS "Z-A local reflection probe contract verified")
